### ISSUE TITLE
failed to parse expression '-'

### ISSUE THREAD

**Issue by falko** [camunda/feel-scala#2]
```
08:32:47.953 [main] INFO  o.o.d.t.r.camunda.CamundaTCKTest - Executing test '0004-simpletable-U-test-01 / 003'

08:32:47.955 [main] ERROR o.o.d.t.r.camunda.CamundaTCKTest - FAILURE: unnexpected exception executing test case '0004-simpletable-U-test-01 / 003'
org.camunda.bpm.dmn.engine.impl.DmnEvaluationException: DMN-01002 Unable to evaluate expression for language 'feel': '-'
	at org.camunda.bpm.dmn.engine.impl.DmnEngineLogger.unableToEvaluateExpression(DmnEngineLogger.java:35) ~[camunda-engine-dmn-7.6.0.jar:7.6.0]
	at org.camunda.bpm.dmn.engine.impl.evaluation.ExpressionEvaluationHandler.evaluateScriptExpression(ExpressionEvaluationHandler.java:100) ~[camunda-engine-dmn-7.6.0.jar:7.6.0]
	at org.camunda.bpm.dmn.engine.impl.evaluation.ExpressionEvaluationHandler.evaluateExpression(ExpressionEvaluationHandler.java:62) ~[camunda-engine-dmn-7.6.0.jar:7.6.0]
	at org.camunda.bpm.dmn.engine.impl.evaluation.DecisionTableEvaluationHandler.evaluateInputEntry(DecisionTableEvaluationHandler.java:198) ~[camunda-engine-dmn-7.6.0.jar:7.6.0]
	at org.camunda.bpm.dmn.engine.impl.evaluation.DecisionTableEvaluationHandler.isConditionApplicable(DecisionTableEvaluationHandler.java:142) ~[camunda-engine-dmn-7.6.0.jar:7.6.0]
	at org.camunda.bpm.dmn.engine.impl.evaluation.DecisionTableEvaluationHandler.evaluateInputForAvailableRules(DecisionTableEvaluationHandler.java:134) ~[camunda-engine-dmn-7.6.0.jar:7.6.0]
	at org.camunda.bpm.dmn.engine.impl.evaluation.DecisionTableEvaluationHandler.evaluateDecisionTable(DecisionTableEvaluationHandler.java:108) ~[camunda-engine-dmn-7.6.0.jar:7.6.0]
	at org.camunda.bpm.dmn.engine.impl.evaluation.DecisionTableEvaluationHandler.evaluate(DecisionTableEvaluationHandler.java:78) ~[camunda-engine-dmn-7.6.0.jar:7.6.0]
	at org.camunda.bpm.dmn.engine.impl.DefaultDmnDecisionContext.evaluateDecision(DefaultDmnDecisionContext.java:82) ~[camunda-engine-dmn-7.6.0.jar:7.6.0]
	at org.camunda.bpm.dmn.engine.impl.DefaultDmnEngine.evaluateDecision(DefaultDmnEngine.java:164) ~[camunda-engine-dmn-7.6.0.jar:7.6.0]
	at org.camunda.bpm.dmn.engine.impl.DefaultDmnEngine.evaluateDecision(DefaultDmnEngine.java:155) ~[camunda-engine-dmn-7.6.0.jar:7.6.0]
	at org.omg.dmn.tck.runner.camunda.CamundaTCKTest.executeTest(CamundaTCKTest.java:132) ~[test-classes/:na]
	at org.omg.dmn.tck.runner.junit4.DmnTckRunner.runChild(DmnTckRunner.java:143) [classes/:na]
	at org.omg.dmn.tck.runner.junit4.DmnTckRunner.runChild(DmnTckRunner.java:1) [classes/:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.omg.dmn.tck.runner.junit4.DmnTckRunner.run(DmnTckRunner.java:112) [classes/:na]
	at org.junit.runners.Suite.runChild(Suite.java:128) [junit-4.12.jar:4.12]
	at org.junit.runners.Suite.runChild(Suite.java:27) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:na]
Caused by: javax.script.ScriptException: failed to parse expression '-':
[1.2] error: `{' expected but end of source found

-
 ^
	at org.camunda.feel.script.FeelScriptEngine$class.compile(FeelScriptEngine.scala:81) ~[feel-engine-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at org.camunda.feel.script.FeelExpressionScriptEngine.compile(FeelExpressionScriptEngine.scala:14) ~[feel-engine-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
	at org.camunda.bpm.dmn.engine.impl.evaluation.ExpressionEvaluationHandler.evaluateScriptExpression(ExpressionEvaluationHandler.java:86) ~[camunda-engine-dmn-7.6.0.jar:7.6.0]
	... 33 common frames omitted
```

**Comment by falko** [comment]
This happened when configuring the engine like this:
```java
        DefaultDmnEngineConfiguration configuration = new DefaultDmnEngineConfiguration();
        configuration.setDefaultInputEntryExpressionLanguage("feel-scala");
        configuration.setDefaultInputExpressionExpressionLanguage("feel-scala");
        configuration.setDefaultLiteralExpressionLanguage("feel-scala");
        configuration.setDefaultOutputEntryExpressionLanguage("feel-scala");
        ctx.runtime = configuration.buildEngine();
```

**Comment by falko** [comment]
It worked when using the CamundaFeelEngineFactory. Could this indicate an issue when selecting feel-scala only for some parts of the decision logic?

**Comment by saig0** [comment]
@falko , you must set the expression language for **inputEntry** to `feel-scala-unary-tests`. Since the FEEL grammar has two entry points: expression and (simple positive) unary tests, the FEEL Scala script engine has also two names, one for each entry point. Note that (simple positive) unary tests is not a part of expression.

Does this solve the issue?

**Comment by falko** [comment]
Thx. That solved it. Here is the working config:

        DefaultDmnEngineConfiguration configuration = new DefaultDmnEngineConfiguration();
        configuration.setFeelEngineFactory(new CamundaFeelEngineFactory());
        configuration.setDefaultInputEntryExpressionLanguage("feel-scala-unary-tests");
        configuration.setDefaultInputExpressionExpressionLanguage("feel-scala");
        configuration.setDefaultLiteralExpressionLanguage("feel-scala");
        configuration.setDefaultOutputEntryExpressionLanguage("feel-scala");
        ctx.runtime = configuration.buildEngine();
