### ISSUE TITLE
Exception when parsing DMNs with FEEL input expression or input entry

### ISSUE THREAD

**Issue by romanha** [camunda/feel-scala#328]
**Describe the bug**
I recently upgraded from Camunda engine 7.8.0 to 7.15.0.
With this upgrade came the new FEEL engine.

Now I have the problem that evaluating a DMN that uses FEEL as input expression **or** input entry, the parsing fails due to a missing method in the fastparse library.

```
ENGINE-16004 Exception while closing command context: 'fastparse.ParserInputSource$fromParserInput fastparse.ParserInputSource$.fromParserInput(java.lang.Object, camundajar.impl.scala.Function1)' java.lang.NoSuchMethodError: 'fastparse.ParserInputSource$fromParserInput fastparse.ParserInputSource$.fromParserInput(java.lang.Object, camundajar.impl.scala.Function1)'
 at org.camunda.feel.impl.parser.FeelParser$.parseExpression(FeelParser.scala:37)
 at org.camunda.feel.FeelEngine.$anonfun$evalExpression$2(FeelEngine.scala:149)
 at org.camunda.feel.FeelEngine.parse(FeelEngine.scala:180)
 at org.camunda.feel.FeelEngine.eval(FeelEngine.scala:175)
 at org.camunda.feel.FeelEngine.evalExpression(FeelEngine.scala:149)
 at org.camunda.bpm.dmn.feel.impl.scala.ScalaFeelEngine.evaluateSimpleExpression(ScalaFeelEngine.java:72)
 at org.camunda.bpm.dmn.engine.impl.evaluation.ExpressionEvaluationHandler.evaluateFeelSimpleExpression(ExpressionEvaluationHandler.java:130)
 at org.camunda.bpm.dmn.engine.impl.evaluation.ExpressionEvaluationHandler.evaluateExpression(ExpressionEvaluationHandler.java:59)
 at org.camunda.bpm.dmn.engine.impl.evaluation.DecisionTableEvaluationHandler.evaluateInputExpression(DecisionTableEvaluationHandler.java:193)
 at org.camunda.bpm.dmn.engine.impl.evaluation.DecisionTableEvaluationHandler.evaluateInput(DecisionTableEvaluationHandler.java:122)
 at org.camunda.bpm.dmn.engine.impl.evaluation.DecisionTableEvaluationHandler.evaluateDecisionTable(DecisionTableEvaluationHandler.java:104)
 at org.camunda.bpm.dmn.engine.impl.evaluation.DecisionTableEvaluationHandler.evaluate(DecisionTableEvaluationHandler.java:81)
 at org.camunda.bpm.dmn.engine.impl.DefaultDmnDecisionContext.evaluateDecision(DefaultDmnDecisionContext.java:85)
 at org.camunda.bpm.dmn.engine.impl.DefaultDmnEngine.evaluateDecision(DefaultDmnEngine.java:167)
 at org.camunda.bpm.engine.impl.dmn.invocation.DecisionInvocation.invoke(DecisionInvocation.java:57)
 at org.camunda.bpm.engine.impl.delegate.DelegateInvocation.proceed(DelegateInvocation.java:58)
 at org.camunda.bpm.engine.impl.delegate.DefaultDelegateInterceptor.handleInvocationInContext(DefaultDelegateInterceptor.java:92)
 at org.camunda.bpm.engine.impl.delegate.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:63)
```

**To Reproduce**

1. Create a DMN with either an input expression or an output entry using the expression language "feel".

```
  <decision id="phoneCallToTrue" name="Return true for phone calls">
    <decisionTable id="decisionTable" hitPolicy="FIRST" preferredOrientation="Rule-as-Row">
      <input id="input_1" label="Media Type">
        <inputExpression id="input_expression_1" typeRef="string" expressionLanguage="feel">
          <text>mediaType</text>
        </inputExpression>
      </input>
      <output id="output_1" label="Result" name="result" typeRef="boolean" />
      <rule id="rule_1">
        <inputEntry id="unary_test_1" expressionLanguage="feel">
          <text>"Phone Call"</text>
        </inputEntry>
        <outputEntry id="output_entry_1" expressionLanguage="feel">
          <text>true</text>
        </outputEntry>
      </rule>
    </decisionTable>
  </decision>
```
2. Start a Camunda process that parses the DMN (e.g. referenced within a BPMN).
3. The parsing fails with the mentioned exception.

**Expected behavior**
The DMN can be parsed correctly and returns the correct result.

**Environment**
* FEEL engine version: [1.13.1-scala-shaded]
* Camunda engine version: [7.15.0]
* Fastparse version: [2.13_2.3.1]
* Java version: Zulu JDK 11.45 (11.0.10) 64-bit

**Comment by romanha** [comment]
I use the Camunda engine and Camunda DMN engine embedded as a library.
The packaging is done with the maven-assembly plugin.

Here is how I solved my problem by excluding the fastparse library:

```
<dependencySet>
   <useProjectArtifact>false</useProjectArtifact>
   <outputDirectory>lib</outputDirectory>
   <useTransitiveDependencies>true</useTransitiveDependencies>
   <useTransitiveFiltering>true</useTransitiveFiltering>
   <includes>
      <include>org.camunda.bpm:camunda-engine</include>
      <include>org.camunda.bpm.dmn:camunda-engine-dmn</include>
   </includes>
   <excludes>
      <!-- Fastparse already comes as part of the "feel-engine-1.13.1-scala-shaded" library, which is part of the Camunda engine. -->
      <exclude>com.lihaoyi:fastparse_2.13</exclude>
   </excludes>
</dependencySet>
```

It was automatically added because the `feel-scala/pom.xml` defines the dependency:

```
<dependency>
   <groupId>com.lihaoyi</groupId>
   <artifactId>fastparse_2.13</artifactId>
   <version>2.3.1</version>
</dependency>
```

**Comment by saig0** [comment]
@romanha thanks for sharing :+1: 

I guess that we should exclude `fastparse` from the shade-plugin, similar to `slf4j-api` [here](https://github.com/camunda/feel-scala/blob/master/pom.xml#L286).

**Comment by bmaupin** [comment]
Thanks to @romanha's suggestion, we were able to fix it in our gradle config:

```groovy
    compile "org.camunda.bpm:camunda-engine:7.16.0"
    compile("org.camunda.bpm.dmn:camunda-engine-dmn:7.16.0") {
        exclude group: 'com.lihaoyi', module: 'fastparse_2.13'
    }
```
